name: textfield_shadow
description: Textfield Shadow is for creating attractive textfield with full customization available and also initial textfield with shadow and prefix and suffix with your choice and many functions for apply more functionality
version: 1.1.0+2
homepage: https://github.com/dhavalgelani99/custom_textfield

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: